### ISSUE TITLE
Not working unless those values are replaced

### ISSUE THREAD

**Issue by nastys** [tonix64/python-installcab#1]
https://github.com/tonix64/python-installcab/blob/06fa88781629f2bc564fbbd9e054047bee259deb/installcab.py#L127

I had to uncomment lines 129-137, otherwise programs that rely on Media Foundation crash because the dlls cannot be found.

**Comment by strycore** [comment]
Can confirm that I had a successful setup once I had uncommented those lines.

**Comment by SergeyLatyshev** [comment]
I can confirm too, with uncommented lines Resident Evil 2 remake works now.

**Comment by strycore** [comment]
The Lutris implementation has incorporated the fix: https://github.com/lutris/lutris/blob/master/lutris/util/wine/cabinstall.py

**Comment by NextGenRyo** [comment]
Still cant do it after starting the install i get this.

`./install-mf-64.sh
mediafoundation
/home/michael/Downloads/python-installcab-master/installcab.py:175: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for registry_key in registry_keys[0].getchildren():
- amd64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_fa8534ab236134c4.manifest (win64)
- wow64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_04d9defd57c1f6bf.manifest (wow64)
Traceback (most recent call last):
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 243, in process_files
    install_dll(file_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 214, in install_dll
    dest_dir = get_dll_destdir(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 65, in get_dll_destdir
    arch = check_dll_arch(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 85, in check_dll_arch
    if 'x86-64' in out:
TypeError: a bytes-like object is required, not 'str'
mf
- amd64_microsoft-windows-mf_31bf3856ad364e35_6.1.7601.17514_none_ab34ec409a77d93c.manifest (win64)
- wow64_microsoft-windows-mf_31bf3856ad364e35_6.1.7601.17514_none_b5899692ced89b37.manifest (wow64)
mfreadwrite
/home/michael/Downloads/python-installcab-master/installcab.py:175: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for registry_key in registry_keys[0].getchildren():
- amd64_microsoft-windows-mfreadwrite_31bf3856ad364e35_6.1.7601.17514_none_177bed732ea3f85f.manifest (win64)
- wow64_microsoft-windows-mfreadwrite_31bf3856ad364e35_6.1.7601.17514_none_21d097c56304ba5a.manifest (wow64)
Traceback (most recent call last):
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 243, in process_files
    install_dll(file_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 214, in install_dll
    dest_dir = get_dll_destdir(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 65, in get_dll_destdir
    arch = check_dll_arch(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 85, in check_dll_arch
    if 'x86-64' in out:
TypeError: a bytes-like object is required, not 'str'
wmadmod
/home/michael/Downloads/python-installcab-master/installcab.py:175: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for registry_key in registry_keys[0].getchildren():
- amd64_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_e474f0ac34979bc4.manifest (win64)
- x86_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_885655287c3a2a8e.manifest (win32)
Traceback (most recent call last):
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 243, in process_files
    install_dll(file_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 214, in install_dll
    dest_dir = get_dll_destdir(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 65, in get_dll_destdir
    arch = check_dll_arch(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 85, in check_dll_arch
    if 'x86-64' in out:
TypeError: a bytes-like object is required, not 'str'
wmvdecod
/home/michael/Downloads/python-installcab-master/installcab.py:175: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for registry_key in registry_keys[0].getchildren():
- amd64_microsoft-windows-wmvdecod_31bf3856ad364e35_6.1.7601.17514_none_20b089c0f6efacae.manifest (win64)
- x86_microsoft-windows-wmvdecod_31bf3856ad364e35_6.1.7601.17514_none_c491ee3d3e923b78.manifest (win32)
Traceback (most recent call last):
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 243, in process_files
    install_dll(file_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 214, in install_dll
    dest_dir = get_dll_destdir(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 65, in get_dll_destdir
    arch = check_dll_arch(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 85, in check_dll_arch
    if 'x86-64' in out:
TypeError: a bytes-like object is required, not 'str'
wmadmod
/home/michael/Downloads/python-installcab-master/installcab.py:175: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  for registry_key in registry_keys[0].getchildren():
- amd64_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_e474f0ac34979bc4.manifest (win64)
- x86_microsoft-windows-wmadmod_31bf3856ad364e35_6.1.7601.17514_none_885655287c3a2a8e.manifest (win32)
Traceback (most recent call last):
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 243, in process_files
    install_dll(file_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 214, in install_dll
    dest_dir = get_dll_destdir(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 65, in get_dll_destdir
    arch = check_dll_arch(dll_path)
  File "/home/michael/Downloads/python-installcab-master/installcab.py", line 85, in check_dll_arch
    if 'x86-64' in out:
TypeError: a bytes-like object is required, not 'str'

Done!
Now you need to get mfplat.dll version 12.0.7601.23471 from elsewhere and place it in your application directory`

I have no idea what its talking about.

**Comment by Jvanrhijn** [comment]
@mixalis1987 Sounds like you're using the wrong version of Python. Is your system version of Python 3.x (output of `python --version`)? If so, try editing the shebang in `cabinstall.py` to say `#! /usr/bin/env python2`.

**Comment by NextGenRyo** [comment]
@Jvanrhijn Hi, my version is Python 3.7.2

**Comment by NextGenRyo** [comment]
@Jvanrhijn Man! thank you that was the problem. got past the errors now. Lets see what happens.

**Comment by NextGenRyo** [comment]
Game works! wow!

**Comment by tonix64** [comment]
Replaced those variables, thanks for reporting and sorry for taking so long to apply.
