### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by habeascorpse** [tonix64/python-installcab#4]
when i tried this: python2 ./installcab.py ~/.cache/winetricks/win7sp1/windows6.1-KB976932-X64.exe mediafoundation

```

mediafoundation
- amd64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_fa8534ab236134c4.manifest (win64)
- wow64_microsoft-windows-mediafoundation_31bf3856ad364e35_6.1.7601.17514_none_04d9defd57c1f6bf.manifest (wow64)
- mf.dll -> /media/alan/938d2aa0-3f75-4a82-a26a-82b3400b0b25/Games/steam/steamapps/compatdata/418370/pfx/drive_c/windows/system32
- mfps.dll -> /media/alan/938d2aa0-3f75-4a82-a26a-82b3400b0b25/Games/steam/steamapps/compatdata/418370/pfx/drive_c/windows/system32
- mf.dll -> /media/alan/938d2aa0-3f75-4a82-a26a-82b3400b0b25/Games/steam/steamapps/compatdata/418370/pfx/drive_c/windows/syswow64
Traceback (most recent call last):
  File "./installcab.py", line 305, in <module>
    process_files(output_files)
  File "./installcab.py", line 246, in process_files
    install_regfile(tmpdir, file_path+".reg", arch)
  File "./installcab.py", line 226, in install_regfile
    subprocess.call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by tonix64** [comment]
it's not finding either wine or wine64 in your $PATH
