### ISSUE TITLE
Script not working unable to determiner why, looks likes something to do with /usr/lib/python2.7/xml/etree/ElementTree.py

### ISSUE THREAD

**Issue by fr1tzz** [tonix64/python-installcab#5]
Trying to get this to work on my Debian testing/buster machine with  Kernel: x86_64 Linux 4.19.0-4-amd64

$ python --version
Python 2.7.16

I've tried also to install this using just the installcab.py script with manualy pointing to the files but it gives me the same error.

Anyone know what I could be doing wrong?

```
fr1tz:python-installcab/ (master) $ ./install-mf-64.sh                                                                                                                                      [15:57:44]
mediafoundation
Traceback (most recent call last):
  File "/home/fr1tz/python-installcab/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/fr1tz/python-installcab/installcab.py", line 233, in process_files
    outdata, arch = load_manifest(file_path)
  File "/home/fr1tz/python-installcab/installcab.py", line 199, in load_manifest
    reg_data, arch = process_manifest(file_path)
  File "/home/fr1tz/python-installcab/installcab.py", line 171, in process_manifest
    elmt = xml.etree.ElementTree.parse(file_name).getroot()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1
mf
Traceback (most recent call last):
  File "/home/fr1tz/python-installcab/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/fr1tz/python-installcab/installcab.py", line 233, in process_files
    outdata, arch = load_manifest(file_path)
  File "/home/fr1tz/python-installcab/installcab.py", line 199, in load_manifest
    reg_data, arch = process_manifest(file_path)
  File "/home/fr1tz/python-installcab/installcab.py", line 171, in process_manifest
    elmt = xml.etree.ElementTree.parse(file_name).getroot()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1
mfreadwrite
Traceback (most recent call last):
  File "/home/fr1tz/python-installcab/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/fr1tz/python-installcab/installcab.py", line 233, in process_files
    outdata, arch = load_manifest(file_path)
  File "/home/fr1tz/python-installcab/installcab.py", line 199, in load_manifest
    reg_data, arch = process_manifest(file_path)
  File "/home/fr1tz/python-installcab/installcab.py", line 171, in process_manifest
    elmt = xml.etree.ElementTree.parse(file_name).getroot()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1
wmadmod
Traceback (most recent call last):
  File "/home/fr1tz/python-installcab/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/fr1tz/python-installcab/installcab.py", line 233, in process_files
    outdata, arch = load_manifest(file_path)
  File "/home/fr1tz/python-installcab/installcab.py", line 199, in load_manifest
    reg_data, arch = process_manifest(file_path)
  File "/home/fr1tz/python-installcab/installcab.py", line 171, in process_manifest
    elmt = xml.etree.ElementTree.parse(file_name).getroot()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1
wmvdecod
Traceback (most recent call last):
  File "/home/fr1tz/python-installcab/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/fr1tz/python-installcab/installcab.py", line 233, in process_files
    outdata, arch = load_manifest(file_path)
  File "/home/fr1tz/python-installcab/installcab.py", line 199, in load_manifest
    reg_data, arch = process_manifest(file_path)
  File "/home/fr1tz/python-installcab/installcab.py", line 171, in process_manifest
    elmt = xml.etree.ElementTree.parse(file_name).getroot()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 2, column 7
wmadmod
Traceback (most recent call last):
  File "/home/fr1tz/python-installcab/installcab.py", line 305, in <module>
    process_files(output_files)
  File "/home/fr1tz/python-installcab/installcab.py", line 233, in process_files
    outdata, arch = load_manifest(file_path)
  File "/home/fr1tz/python-installcab/installcab.py", line 199, in load_manifest
    reg_data, arch = process_manifest(file_path)
  File "/home/fr1tz/python-installcab/installcab.py", line 171, in process_manifest
    elmt = xml.etree.ElementTree.parse(file_name).getroot()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 1

Done!
Now you need to get mfplat.dll version 12.0.7601.23471 from elsewhere and place it in your application directory

```

**Comment by tonix64** [comment]
You might need to install python-xml package for your distro.

**Comment by tonix64** [comment]
actually looking at the backtrace looks like it doesn't find the extracted manifest xml files from the cabinet for some reason.

you could try printing file_path in the line before

`reg_data, arch = process_manifest(file_path)`

and figure out what path it's showing and why it's not finding it.
